plan error::catch_plan {
 run_plan('error::err', '_catch_errors' => true)
}
